# Generated by Django 5.0.4 on 2024-04-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Новый'), (1, 'Проверен')], default=0),
        ),
    ]
