# Generated by Django 5.0.4 on 2024-04-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='deal_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Сделка'),
        ),
    ]
