# Generated by Django 5.0.4 on 2024-05-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_operations_deal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='counterparty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Контрагента'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='deal_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Сделки'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Новый'), (1, 'Проверено и отправлено'), (2, 'Отклонено администратором')], default=0),
        ),
    ]
