# Generated by Django 5.0.6 on 2024-06-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_operations_counterparty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='rejected_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к отчёту'),
        ),
    ]
